name: Test Execution

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select Test Environment
        type: choice
        options:
          - sandbox
          - prod

      browser:
        description: Select Browser
        type: choice
        options:
          - chrome
          - firefox
          - edge

      headless:
        description: Run in Headless Mode
        type: boolean
        default: true

      parallel:
        description: Run Test in Parallel
        type: boolean
        default: false

      test_name:
        description: Test Method / Test class Name (e.g., MyTestClass#myTestMethod or MyTestClass1, MyTestClass2)
        required: false
        type: string

jobs:
  execute-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository to Runner
        uses: actions/checkout@v4

      - name: Run Maven Test
        run: docker compose up -d
        env:
          ENV: ${{ inputs.env }}
          BROWSER: ${{ inputs.browser }}
          HEADLESS: ${{ inputs.headless }}
          PARALLEL: ${{ inputs.parallel }}
          TEST: ${{ inputs.test_name }}

      - name: Docker Compose Down
        if: always()
        run: |
          docker compose logs selenium-hub
          docker compose logs chrome
          docker compose logs firefox
          docker compose logs edge
          docker compose logs tests
          docker compose down

      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 3
